service: coffee-is-work-backend

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  organisationsTableName: ${self:custom.stage}-OrganisationsTable
  usersTableName: ${self:custom.stage}-UsersTable

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  environment:
    ORGANISATIONS_TABLE: ${self:custom.organisationsTableName}
    USERS_TABLE: ${self:custom.usersTableName}
    POST_CONFIRMATION_LAMBDA: arn:aws:lambda:${self:provider.region}:866195672519:function:${self:service}-${self:provider.stage}-postConfirmation
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ OrganisationsTable, Arn]
        - "Fn::GetAtt": [ UsersTable, Arn]
    - Effect: "Allow"
      Action:
        - ses:SendEmail
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
      Resource:
        - "*"
  iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/AmazonCognitoReadOnly'

functions:
  add:
    handler: add.main
    events:
      - http:
          path: users
          method: post
          cors: true
          authorizer: aws_iam
  list:
    handler: list.main
    events:
      - http:
          path: users
          method: get
          cors: true
          authorizer: aws_iam
  pair:
    handler: pair.main
    events:
      - http:
          path: pair
          method: get
          cors: true
          authorizer: aws_iam
  postConfirmation:
    handler: postConfirmation.main
  emailPair:
    handler: emailPair.main
    events:
      - http:
          path: emailPair
          method: post
          cors: true
          authorizer: aws_iam
  emailConfirmUsers:
    handler: emailConfirmUsers.main
  confirm:
    handler: confirmUser.main
    events:
      - http:
          path: confirm
          method: post
          cors: true
  requestUnsubscribe:
    handler: requestUnsubscribe.main
    events:
      - http:
          path: unsubscribe/request
          method: post
          cors: true
  confirmUnsubscribe:
    handler: confirmUnsubscribe.main
    events:
      - http:
          path: unsubscribe/confirm
          method: post
          cors: true

resources:
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
  - ${file(resources/dynamodb-tables.yml)}
  - Resources:
      PostConfirmationTriggerInvokePermission:
        Type: AWS::Lambda::Permission
        Properties:
          Action: lambda:InvokeFunction
          Principal: cognito-idp.amazonaws.com
          SourceArn:
            Fn::GetAtt: [ "CognitoUserPool", "Arn" ]
          FunctionName: "${self:provider.environment.POST_CONFIRMATION_LAMBDA}"